-- COLOCAR O BANCO A SER UTILIZADO
USE [DB_TESTE_VAM]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ALTERAR O NOME DA PROCEDURE
CREATE PROCEDURE [dbo].[Modelo_Procedure]
AS
BEGIN
	BEGIN TRY
		PRINT('TESTE')
		-- CODIGO A SER EXECUTADO
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE()
				,@ErrorSeverity INT = ERROR_SEVERITY()
				,@ErrorState INT = ERROR_STATE();
		-- PROC QUE GUARDA ERRO NA HISTÓRICA (PROBLEMA NESSA PROC)
		EXEC [DB_TESTE_VAM].DBO.Log_ProcedureCall @ObjectID = @@PROCID;

		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
END