EXEC DB_TESTE_VAM.DBO.PR_DISPARO_AUTOMATICO 'DB_TESTE_VAM.dbo.VAM_TESTE_PROCEDURE', 'SAUDE'

SELECT ORIGEM, COUNT(*) FROM DB_TESTE_VAM.dbo.VAM_TESTE_PROCEDURE WHERE EXCLUIR IS NULL GROUP BY ORIGEM

SELECT TOP 500 * FROM DB_TESTE_VAM.dbo.VAM_TESTE_PROCEDURE

DROP TABLE DB_TESTE_VAM.dbo.VAM_TESTE_PROCEDURE